### PR TITLE
Debug ftrace v2

### PR DESCRIPTION
**Pull request by unicornx**
second PR, if no more comments, please help merge, thanks.

### CODE REVIEW

**Comment by unicornx** [comment]
One question, the PR target should be `tinyclub:develop`, not `tinyclub:master`, right?

**Comment by lzufalcon** [comment]
@unicornx yes, well merge it asap.

**Comment by cee1** [comment]
Hi，能把 3 次 commits  merge 成一个不？

i.e. git rebase -i b4002c6

然后：

s       updated after 2nd review
s       updated after review
pick zh/dbg_portal/kernel_trace_and_profile/Ftrace/Ftrace.md

**Comment by unicornx** [comment]
Hi, I have finished the rebase, please help review and merge it if no more questions.

**Review by cee1 — APPROVED** [review]

**Comment by lzufalcon** [comment]
@unicornx @cee1 这笔合并了吗？合并完就可以 close 了。

**Comment by cee1** [comment]
"Changes approved" 应该就是合并的意思吧？Close and comment！

**Pull request merged**
